2020-06-20 12:08:44,698 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute']
2020-06-20 12:08:44,704 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute', u'instances']
2020-06-20 12:08:44,724 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute', u'instances', u'create']
2020-06-20 12:08:44,904 DEBUG    root            Running [gcloud.compute.instances.create] with arguments: [--accelerator: "OrderedDict([(u'type', 'nvidia-tesla-p100'), (u'count', 1)])", --boot-disk-size: "214748364800", --image-family: "pytorch-latest-gpu", --image-project: "deeplearning-platform-release", --machine-type: "n1-highmem-8", --maintenance-policy: "TERMINATE", --metadata: "OrderedDict([(u'install-nvidia-driver', u'True')])", --preemptible: "True", --zone: "us-central1-f", INSTANCE_NAMES:1: "[u'M5U-instance']"]
2020-06-20 12:08:51,797 INFO     ___FILE_ONLY___ Enabling service [compute.googleapis.com] on project [884648968654]...

2020-06-20 12:10:20,264 INFO     ___FILE_ONLY___ Operation "operations/acf.9708289e-345e-4c48-ad50-9596cc50a012" finished successfully.

2020-06-20 12:10:26,254 DEBUG    root            (gcloud.compute.instances.create) Could not fetch resource:
 - Invalid value for field 'resource.name': 'M5U-instance'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
Traceback (most recent call last):
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/Users/shu/google-cloud-sdk/lib/surface/compute/instances/create.py", line 428, in Run
    return compute_client.MakeRequests(requests)
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 103, in MakeRequests
    errors, error_message='Could not fetch resource:')
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 119, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 131, in RaiseException
    errors))
ToolException: Could not fetch resource:
 - Invalid value for field 'resource.name': 'M5U-instance'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'

2020-06-20 12:10:26,258 ERROR    root            (gcloud.compute.instances.create) Could not fetch resource:
 - Invalid value for field 'resource.name': 'M5U-instance'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'

